# -*- coding: utf-8 -*-
"""M_Brain_Scan_Kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hVph4CNZnYmNq0mqjjpDiNkvg-uK1TX
"""

# Import Libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from PIL import Image

# Image Path
image_path= "baby.jpg" # replace with your image path

# Image load and resize
img = Image.open(image_path)
img=img.resize((200,200))
img_array=np.array(img)

# Deisplay the original image
plt.figure(figsize=(10,6))
plt.imshow(img)
plt.title("Original Image")

# Define no of cluster and reshape the image for KMeans

k=9
h,w,c= img_array.shape
new_img_pixels = img_array.reshape(h * w,c)

# Perform KMeans Clustering

kmeans=KMeans(n_clusters=k,n_init=10)
labels= kmeans.fit_predict(new_img_pixels)

# Create Segmented Image
segmented_image = kmeans.cluster_centers_[labels].reshape(h, w, c).astype(np.uint8)

# Display the Segmented Image
plt.imshow(segmented_image)
plt.title(f"segmented image (k={k})")

# Working with Brain Scan Image
pip install pydicom

import pydicom

dicom_path='/content/Vida_Head.MR.Comp_DR-Gain_DR.1005.1.2021.04.27.14.20.13.818.14380335 (1) (1).dcm'

# Read Dicom image
dataset = pydicom.dcmread(dicom_path)
img_array = dataset.pixel_array.astype(float)

# Normalize pixel values using min max scaler.
img_array= (img_array - np.min(img_array))/(np.max(img_array) - np.min(img_array))
plt.figure(figsize=(10,6))
plt.imshow(img_array, cmap=plt.cm.gray)
plt.title('Orignial Medical Image')

# Reshape for K-Means
h,w = img_array.shape
pixels=img_array.reshape(h*w,1)

#Perform K-Means
k=4
kmeans=KMeans(n_clusters=k, random_state=42, n_init=10)
label=kmeans.fit_predict(pixels)

segmented_image = kmeans.cluster_centers_[label].reshape(h,w)
plt.figure(figsize=(10,6))
plt.imshow(segmented_image,cmap=plt.cm.gray)
plt.title(f'Segmented Medical Image (k={k})')
plt.axis('off')

# Elbow Method

sse=[]
K=range(2,11) # Test k values from 2-10

for kValue in K :
  kmeans_elbow = KMeans(n_clusters=kValue, n_init=10, random_state=42)
  kmeans_elbow.fit(pixels)
  sse.append(kmeans_elbow.inertia_)

plt.figure(figsize=(10,6))
plt.plot(K,sse,marker='o')
plt.xlabel('Number of Clusters(k)')
plt.ylabel('Sum of Squared Error (SSE)')
plt.title(' Elbow method for Optimal k')
plt.xticks(K)
plt.grid(True)
plt.show()

# Display figure for each segment.

for i in range(k):
  cluster_mask = (label.reshape(h,w) == i)
  segment= img_array * cluster_mask

  plt.figure()
  plt.imshow(segment, cmap=plt.cm.gray)
  plt.title(f'segment {i+1}')
  plt.axis('off')
  plt.show()